# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dicty' do
  # Comment the next line if you don't want to use dynamic frameworks
  inhibit_all_warnings!

  use_frameworks!

  # Pods for Dicty
  pod 'AWSTranslate'
  pod 'Sourcery'
  pod 'Eureka'
  pod 'SwiftLint'
  pod 'TinyConstraints'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'DictyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DictyUITests' do
    # Pods for testing
  end

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end
