# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dicty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dicty
  pod 'AWSTranslate', '~> 2.6.19'
  pod 'Sourcery'
  pod 'Eureka'
  
  target 'DictyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DictyUITests' do
    # Pods for testing
  end

end
